---
- name: Create users and Groups
  hosts: hosts
  become: true
  roles:
    - users
    
- name: Enable PowerTools repository
  hosts: hosts 
  become: true    
  roles:
    - powertools
    
- name: Create LVM and mounting it.
  hosts: hosts
  become: true
  roles:
    - lvm 

