---
# tasks file for main    
- name: Install lvm2 package
  yum:
    name: lvm2
    state: present

- name: Create cache partition
  parted:
    device: /dev/sdb
    number: 1
    state: present
    align: optimal
    part_start: 1MB
    part_end: 40%
    fs_type: ext4

- name: Create physical volume on cache partition
  become: true
  command: pvcreate /dev/sdb1

- name: Create volume group
  become: true
  command: vgcreate cache_vg /dev/sdb1

- name: Create cache logical volume
  become: true
  command: lvcreate --type cache-pool --name cache_lv -L 2G cache_vg /dev/sdb1

- name: Create backing logical volume
  become: true
  command: lvcreate --name backing_lv -l 100%FREE cache_vg

- name: Format cache volume
  filesystem:
    fstype: ext4
    dev: /dev/mapper/cache_vg-backing_lv
    force: yes

- name: Create mount point directory
  file:
    path: /data/dir
    state: directory

- name: Mount cache volume
  mount:
    path: /data/dir
    src: /dev/mapper/cache_vg-backing_lv
    fstype: ext4
    opts: defaults
    state: mounted

- name: Add cache volume to fstab
  lineinfile:
    path: /etc/fstab
    line: '/dev/mapper/cache_vg-backing_lv /data/dir ext4 defaults 0 0'
    state: present